michimani/gotwi

- README.md
- api/resource/users/users_by.go
- params/users_by.go
- types/response/users_user_lookup.go
> support GET /2/users/by API #5

- .github/workflows/onlytest.yml
- .github/workflows/release.yml
> add github actions #8

- internal/util/response.go
- users/api_user_lookup.go
- users/types/userlookup_parameter.go
> refactor user lookup apis #20

- LICENCE
> add LICENCE #23

- CREDITS
> add CREDITS #25

- client.go
- internal/gotwierrors/error.go
- internal/util/response.go
- resources/error.go
- users/api_user_lookup.go
- users/types/userlookup_response.go
- users/types/userlookup_response_test.go
> support partial error struct 

- README.md
- fields/media_fields.go
- fields/place_fields.go
- fields/poll_fields.go
- fields/tweet_fields.go
- fields/user_fields.go
- tweets/api_tweet_lookup.go
- tweets/types/tweet_lookup_parameter.go
- tweets/types/tweet_lookup_parameter_test.go
- tweets/types/tweet_lookup_response.go
- tweets/types/tweet_lookup_response_test.go
> support GET /2/tweets API #13

- README.md
- resources/meta.go
- resources/tweet.go
- users/api_follows.go
- users/types/follows_parameter.go
- users/types/follows_parameter_test.go
- users/types/follows_response.go
- users/types/follows_response_test.go
> support GET /2/users/:id/following API #15

- README.md
- users/api_follows.go
- users/types/follows_parameter.go
- users/types/follows_response.go
> support GET /2/users/:id/followers API #50

- fields/exclude.go
- fields/expansions.go
> fix fields #126

- README.md
- fields/expansions.go
- fields/space_fields.go
- fields/state.go
- resources/space.go
- spaces/api_search_spaces.go
- spaces/types/search_spaces_parameter.go
- spaces/types/search_spaces_parameter_test.go
- spaces/types/search_spaces_response.go
- spaces/types/search_spaces_response_test.go
> support GET /2/spaces/search #122

- README.md
- spaces/api_spaces_lookup.go
- spaces/types/search_spaces_parameter.go
- spaces/types/spaces_lookup_parameter.go
- spaces/types/spaces_lookup_parameter_test.go
- spaces/types/spaces_lookup_response.go
- spaces/types/spaces_lookup_response_test.go
> support GET /2/spaces/:id #119

- README.md
- spaces/api_spaces_lookup.go
- spaces/types/spaces_lookup_parameter.go
- spaces/types/spaces_lookup_parameter_test.go
- spaces/types/spaces_lookup_response.go
- spaces/types/spaces_lookup_response_test.go
> support GET /2/spaces #120

- README.md
- resources/meta.go
- spaces/api_spaces_lookup.go
- spaces/types/spaces_lookup_parameter.go
- spaces/types/spaces_lookup_parameter_test.go
- spaces/types/spaces_lookup_response.go
- spaces/types/spaces_lookup_response_test.go
> support GET /2/spaces/by/creator_ids #121

- README.md
- resources/meta.go
- resources/stream_rule.go
- tweets/api_filtered_stream.go
- tweets/types/filtered_stream_parameter.go
- tweets/types/filtered_stream_parameter_test.go
- tweets/types/filtered_stream_response.go
- tweets/types/filtered_stream_response_test.go
> support GET /2/tweets/search/stream/rules #39

- README.md
- fields/list_fields.go
- lists/api_list_lookup.go
- lists/types/list_lookup_parameter.go
- lists/types/list_lookup_parameter_test.go
- lists/types/list_lookup_response.go
- lists/types/list_lookup_response_test.go
- resources/list.go
- utli.go
> support GET /2/lists/:id #133

- client.go
- lists/types/list_lookup_response_test.go
- resources/error.go
- resources/fields.go
- resources/meta.go
- resources/space.go
- resources/stream_rule.go
- resources/tweet.go
- resources/tweet_count.go
- resources/user.go
- spaces/types/search_spaces_response_test.go
- spaces/types/spaces_lookup_response_test.go
- tweets/types/filtered_stream_response_test.go
- tweets/types/search_tweets_response_test.go
- tweets/types/tweet_counts_response_test.go
- tweets/types/tweet_likes_response_test.go
- tweets/types/tweet_lookup_response_test.go
- tweets/types/tweet_retweets_response_test.go
- tweets/types/tweet_timelines_response_test.go
- users/types/blocks_response_test.go
- users/types/follows_response_test.go
- users/types/mutes_response_test.go
- users/types/user_lookup_response_test.go
- utli.go
> fix resource field type #143

- README.md
- lists/api_list_lookup.go
- lists/types/list_lookup_parameter.go
- lists/types/list_lookup_parameter_test.go
- lists/types/list_lookup_response.go
- lists/types/list_lookup_response_test.go
- resources/meta.go
> GET /2/users/:id/owned_lists #134

- README.md
- lists/api_list_members.go
- lists/types/list_members_parameter.go
- lists/types/list_members_parameter_test.go
- lists/types/list_members_response.go
- lists/types/list_members_response_test.go
- resources/meta.go
> support GET /2/lists/:id/members #137

- README.md
- lists/api_list_tweets_lookup.go
- lists/types/list_tweets_lookup_parameter.go
- lists/types/list_tweets_lookup_parameter_test.go
- lists/types/list_tweets_lookup_response.go
- lists/types/list_tweets_lookup_response_test.go
- resources/meta.go
> support GET /2/lists/:id/tweets #135

- README.md
- lists/api_pinned_lists.go
- lists/types/pinned_lists_parameter.go
- lists/types/pinned_lists_parameter_test.go
- lists/types/pinned_lists_response.go
> support GET /2/users/:id/pinned_lists #140

- README.md
- lists/api_list_follows.go
- lists/types/list_follows_parameter.go
- lists/types/list_follows_parameter_test.go
- lists/types/list_follows_response.go
- lists/types/list_follows_response_test.go
- resources/meta.go
> support GET /2/lists/:id/followers #138

- README.md
- lists/api_list_follows.go
- lists/types/list_follows_parameter.go
- lists/types/list_follows_parameter_test.go
- lists/types/list_follows_response.go
- lists/types/list_follows_response_test.go
- resources/meta.go
> support GET /2/users/:id/followed_lists #139

- README.md
- lists/api_list_members.go
- lists/types/list_members_parameter.go
- lists/types/list_members_parameter_test.go
- lists/types/list_members_response.go
- lists/types/list_members_response_test.go
- resources/meta.go
> support GET /2/users/:id/list_memberships #136

- README.md
- tweets/api_manage_tweets.go
- tweets/types/manage_tweets_parameter.go
- tweets/types/manage_tweets_parameter_test.go
- tweets/types/manage_tweets_response.go
> support POST /2/tweets #155

- README.md
- tweets/api_manage_tweets.go
- tweets/types/manage_tweets_parameter.go
- tweets/types/manage_tweets_parameter_test.go
- tweets/types/manage_tweets_response.go
> support DELETE /2/tweets #156

- client.go
- oauth1.go
- tweets/types/search_tweets_parameter.go
- tweets/types/search_tweets_parameter_test.go
> fix craeting OAuth1.0 signature #162

- CHANGELOG_DEV.md
> add CHANGELOG_DEV #165

- .github/workflows/onlytest.yml
- .github/workflows/release.yml
- README.md
> add uploading code coverage step #168

- client_test.go
- export_test.go
- oauth1.go
- oauth1_test.go
- oauth2_test.go
- util_test.go
> add tests #171

- .github/workflows/onlytest.yml
- internal/util/header_test.go
- internal/util/rate_limit_test.go
> add tests #174

- .github/workflows/onlytest.yml
- .github/workflows/release.yml
> use codecov-action@v2 #177

- lists/types/list_follows_parameter_test.go
- lists/types/list_follows_response_test.go
- lists/types/list_members_parameter_test.go
- lists/types/list_members_response_test.go
- lists/types/manage_lists_parameter_test.go
- lists/types/manage_lists_response_test.go
- lists/types/pinned_lists_parameter_test.go
- lists/types/pinned_lists_response_test.go
- spaces/types/spaces_lookup_parameter_test.go
- tweets/types/hide_replies_response_test.go
- tweets/types/manage_tweets_response_test.go
- tweets/types/tweet_likes_parameter_test.go
- tweets/types/tweet_likes_response_test.go
- tweets/types/tweet_retweets_response_test.go
- tweets/types/tweet_timelines_parameter_test.go
- tweets/types/tweet_timelines_response_test.go
- users/types/blocks_parameter_test.go
- users/types/blocks_response_test.go
- users/types/follows_parameter_test.go
- users/types/follows_response_test.go
- users/types/mutes_parameter_test.go
- users/types/mutes_response_test.go
> add tests vo3 #179

- client.go
- client_test.go
- export_test.go
- oauth2.go
- oauth2_test.go
> add tests vo4 #181

- README.md
- users/api_user_lookup.go
- users/types/user_lookup_parameter.go
- users/types/user_lookup_parameter_test.go
- users/types/user_lookup_response.go
- users/types/user_lookup_response_test.go
> support GET /2/users/me #183

- client.go
> use io instead of ioutil

- users/api_user_lookup.go
> fix comment

- .github/workflows/onlytest.yml
- README.md
- spaces/api_spaces_lookup.go
- spaces/types/spaces_lookup_parameter.go
- spaces/types/spaces_lookup_parameter_test.go
- spaces/types/spaces_lookup_response.go
- spaces/types/spaces_lookup_response_test.go
> support GET /2/spaces/:id/buyers

- README.md
- resources/meta.go
- spaces/api_spaces_lookup.go
- spaces/types/spaces_lookup_parameter.go
- spaces/types/spaces_lookup_parameter_test.go
- spaces/types/spaces_lookup_response.go
- spaces/types/spaces_lookup_response_test.go
> support GET /2/spaces/:id/tweets

- client.go
- client_test.go
- mock_test.go
- oauth2_test.go
> add client test

- lists/types/list_follows_parameter.go
- lists/types/list_lookup_parameter.go
- lists/types/list_members_parameter.go
- lists/types/list_tweets_lookup_parameter.go
- lists/types/pinned_lists_parameter.go
- spaces/types/search_spaces_parameter.go
- spaces/types/spaces_lookup_parameter.go
- tweets/types/filtered_stream_parameter.go
- tweets/types/search_tweets_parameter.go
- tweets/types/tweet_counts_parameter.go
- tweets/types/tweet_likes_parameter.go
- tweets/types/tweet_lookup_parameter.go
- tweets/types/tweet_retweets_parameter.go
- tweets/types/tweet_timelines_parameter.go
- users/types/blocks_parameters.go
- users/types/follows_parameter.go
- users/types/mutes_parameters.go
- users/types/user_lookup_parameter.go
> Remove unnecessary steps #206

- .github/workflows/onlytest.yml
- .github/workflows/release.yml
- doc.go
> update setup-go, checkout to v3 #208

- README.md
- client.go
- client_test.go
> generate client with access token #221

- CHANGELOG_DEV.md
- README.md
- tweets/api_bookmarks.go
- tweets/types/bookmarks_parameter.go
- tweets/types/bookmarks_parameter_test.go
- tweets/types/bookmarks_response.go
- tweets/types/bookmarks_response_test.go
Close #215
Close #216
Close #217
> release v0.10.2

- _examples/0_generate_access_token_with_pkce/README.md
> improve example #227

- README.md
- compliance/api_batch_compliance.go
- compliance/types/batch_compliance_parameter.go
- compliance/types/batch_compliance_parameter_test.go
- compliance/types/batch_compliance_response.go
- compliance/types/batch_compliance_response_test.go
- resources/compliance.go
> support POST /2/compliance/jobs #125

- README.md
- compliance/api_batch_compliance.go
- compliance/types/batch_compliance_parameter.go
- compliance/types/batch_compliance_parameter_test.go
- compliance/types/batch_compliance_response.go
- compliance/types/batch_compliance_response_test.go
> support GET /2/compliance/jobs #124

- README.md
- compliance/api_batch_compliance.go
- compliance/types/batch_compliance_parameter.go
- compliance/types/batch_compliance_parameter_test.go
- compliance/types/batch_compliance_response.go
- compliance/types/batch_compliance_response_test.go
> support GET /2/compliance/jobs/:id #123

- CHANGELOG_DEV.md
- README.md
- compliance/api_batch_compliance.go
- compliance/types/batch_compliance_parameter.go
- compliance/types/batch_compliance_parameter_test.go
- compliance/types/batch_compliance_response.go
- compliance/types/batch_compliance_response_test.go
- resources/compliance.go
Close #123 Close #124 Close #125
> release v0.10.3

- README.md
- _examples/3_sample_stream/go.mod
- _examples/3_sample_stream/main.go
- _examples/3_sample_stream/sample_stream.go
- _examples/README.md
- client.go
- client_test.go
- export_test.go
- mock_test.go
- oauth2_test.go
- stream_client.go
- stream_client_test.go
- tweet/volumestream/api.go
- tweet/volumestream/types/parameter.go
- tweet/volumestream/types/parameter_test.go
- tweet/volumestream/types/response.go
- tweet/volumestream/types/response_test.go
- typed_client.go
- typed_client_test.go
> support GET /2/tweets/sample/stream #41

- README.md
- resources/meta.go
- tweet/filteredstream/api.go
- tweet/filteredstream/types/parameter.go
- tweet/filteredstream/types/parameter_test.go
- tweet/filteredstream/types/response.go
- tweet/filteredstream/types/response_test.go
> support POST /2/tweets/search/stream/rules #38

- tweet/searchtweet/types/parameter.go
- tweet/searchtweet/types/parameter_test.go
> feat: support sort_order parameter at Search Tweet API #263

- tweet/managetweet/types/parameter.go
- tweet/managetweet/types/parameter_test.go
> feat: support qupte_tweet_id parameter at POST /2/tweets #267

- tweet/volumestream/types/parameter.go
- tweet/volumestream/types/parameter_test.go
> feat: support backfill_minutes parameter at GET /2/tweets/sample/stream #269

- tweet/quotetweet/types/parameter.go
- tweet/quotetweet/types/parameter_test.go
> feat: support exclude parameter at GET /2/tweets/:id/quote_tweets #271

- tweet/retweet/types/parameter.go
- tweet/retweet/types/parameter_test.go
> feat: support max_results and pagination_token parameter at GET /2/tweets/:id/retweeted_by #270

- tweet/like/types/parameter.go
- tweet/like/types/parameter_test.go
> feat: support max_results and pagination_token parameter at GET /2/tweets/:id/liking_users #272

- tweet/quotetweet/types/parameter.go
- tweet/quotetweet/types/parameter_test.go
> fix: invalid exclude parameter type #279

- list/managelist/types/response.go
- list/managelist/types/response_test.go
> fix: response struct for PUT /2/lists/:id #284

- resources/meta.go
> fix: remove invalid field from TweetTimelineMeta #288

- resources/error.go
- resources/tweet.go
> fix: invalid field name

- .github/workflows/onlytest.yml
- .github/workflows/release.yml
- go.mod
> bump Go version to 1.20

- README.md
- _examples/README.md
> add description of plan restrictions in README

- fields/user_fields.go
- resources/user.go
Adding mentioned field to the user_fields object
Reference
https://developer.x.com/en/docs/x-api/users/lookup/api-reference/get-users-me
> Feature: add 'most_recent_tweet_id' to the user_fields
